# Generated by Django 4.0.2 on 2022-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
