# Generated by Django 4.0.2 on 2022-02-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_purchase_purchasereturns'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
