# Generated by Django 4.0.2 on 2022-02-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
